### ISSUE TITLE
noGPU docker fails with error

### ISSUE THREAD

**Issue by miltondts** [mohit1997/DNA_Compression#14]
I'm trying to use the noGPU docker, but it fails with the following error:
```
ERROR: Invalid requirement: 'keras=2.2.2'
Hint: = is not a valid operator. Did you mean == ?
```

After correcting this error. The docker builds, but then when executing `./run_experiments.sh biLSTM` it fails with:
```
keras@e5a0d487f397:/src/workspace/src$ ./run_experiments.sh biLSTM
Requirement already satisfied: tqdm in /opt/conda/lib/python3.6/site-packages (4.47.0)
../data/processed_files/Caenorhabditis_elegans.WBcel235.dna.chromosome.I.npy
Caenorhabditis_elegans.WBcel235.dna.chromosome.I
../data/processed_files/Caenorhabditis_elegans.WBcel235.dna.chromosome.I.param.json
cmp: ../data/compressed/Caenorhabditis_elegans.WBcel235.dna.chromosome.I/biLSTM.reconstructed.txt: No such file or directory
2
cmp: ../data/compressed/Caenorhabditis_elegans.WBcel235.dna.chromosome.I/biLSTM.reconstructed.txt: No such file or directory
continuing
Starting training ...
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:521: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:522: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "/src/keras/__init__.py", line 3, in <module>
    from tensorflow.keras.layers.experimental.preprocessing import RandomRotation
ModuleNotFoundError: No module named 'tensorflow.keras'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "trainer.py", line 4, in <module>
    from keras.layers.embeddings import Embedding
  File "/src/keras/__init__.py", line 6, in <module>
    'Keras requires TensorFlow 2.2 or higher. '
ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow`
```

Any idea what might be wrong?

**Comment by mohit1997** [comment]
Hi,
can you please try with alternative installation since CUDA is not required for using CPU implementation?
```bash
git clone --single-branch --branch noGPU https://github.com/mohit1997/DeepZip.git
cd DeepZip
python3 -m venv tf
source tf/bin/activate
bash install.sh
```

**Comment by miltondts** [comment]
Ah yes, I was using the docker because on my distribution (archlinux) I get the following error:
```
Successfully installed pip-20.1.1
ERROR: Could not find a version that satisfies the requirement tensorflow==1.8 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1)
ERROR: No matching distribution found for tensorflow==1.8
```
Apparently, this is due to python3.8 not being compatible with tensorflow==1.8. After installing python3.6 the program is now running.

Thank you for the quick response.
