### ISSUE TITLE
reconstructed file same as the original file.

### ISSUE THREAD

**Issue by kv304** [mohit1997/DNA_Compression#17]
Hi , I was trying to compress a normal text file , the model runs on all epochs and shows the loss improving significantly , the compressor file also executes with no error.However , the result gives me the exact same file labelled as reconstructed. I have tried using multiple models and the probabilities of the model were also decent.Also the files mentioned in the paper like xor30 etc have just two symbols.So Is their something wrong in the way I am trying to understand and run the algorithm?.Does it require a different approach for a file that has multiple symbols?

**Comment by mohit1997** [comment]
I think when you run DeepZip, it compresses and decompresses the input file. So reconstructed file should be same as input because that is the output of decompression. Please check `./data/compressed` directory to get your compressed file. Apart from that nothing sounds wrong in what you are observing.

**Comment by kv304** [comment]
Can You tell me what is the compressed filed labelled as in the folder? And Can I view it in python?

**Comment by mohit1997** [comment]
Check `./data/compressed/INPUT_FILE_NAME/biLSTM.combined` if you used biLSTM. If you used some other model, it would be named `MODEL_NAME.combined` in the same folder as above.

**Comment by kv304** [comment]
Can I view it's contents somehow?

**Comment by mohit1997** [comment]
It’s just a binary file, I suppose you can read it with python or some editors as well. But it wouldn’t have any interpretation.

**Comment by kv304** [comment]
I was hoping to see the output of the arithmetic encoders like the encoded floating numbers(or the tag for a word as they call it in the algorithm),that are generated out from actual data.

**Comment by mohit1997** [comment]
You can refer to this implementation if you are interested.
[https://github.com/nayuki/Reference-arithmetic-coding](https://github.com/nayuki/Reference-arithmetic-coding)

**Comment by kv304** [comment]
okay thanks , I had Some more doubt about the algo ,
1) the probabilities that the model predicts , are those positional or static? Like will the probabilities be different for same symbol based on its positional occurrence or will the symbol have a constant overall probability for the file which is used for all it's occurrences
2)if the probabilities are positional then for the best case scenario the actual symbol at that position would have a probability as 1 while others would be zero , how does this positional probability vector(like 1,0,0,0) work in compression?
3) How does the algo identify a sequence to encode , like are there any delimiters which break the file into sequences ?

**Comment by mohit1997** [comment]
1. I would use the word contextual instead of positional. The probabilities depend on the past few symbols [64 specifically in our implementation]. The best-case scenario is applicable for deterministic sequences such as xor10,20,30.. and so on. If that is the case, then you just need to store the first symbol and the rest takes negligible bytes.
2. I did not understand your question exactly. The file is read at a byte level and is, therefore, always a sequence of bytes.

For more details, I encourage you to refer to our paper: [DeepZip](https://arxiv.org/abs/1811.08162)

**Comment by kv304** [comment]
Thanks, I am going through the paper.About the 2nd question , as far as I understand it arithmetic encoding generates a floating number for a given text sequence , so what sequence are we giving it to encode?and how are we giving it to the encoder?

**Comment by shubhamchandak94** [comment]
The arithmetic coders in practice don't usually work with floats, they typically internally use integers and use a variant called range coding. You can think of the arithmetic coder as having an internal state, which gets updated at every encoding step. At certain steps the encoder produces output bits which eventually form the compressed bitstream. The input to the arithmetic coder at every step is (i) the symbol to be encoded, and (ii) a probability model over all symbols. In DeepZip, the symbols to be encoded are simply the symbols in the file to be compressed. The probability model is based on the neural network output and depends on the context of the symbol. If you look at <https://github.com/mohit1997/DeepZip/blob/master/src/compressor.py#L108>:

```
prob = model.predict(X[i,:].reshape(1,-1), batch_size=1)
cumul[1:] = np.cumsum(prob*10000000 + 1)
enc.write(cumul, y_original[i][0])
```
The first line gets the probabilities from the neural net, the second line computes the cumulative distribution from these probabilities, and the third line does the arithmetic encoding step. Due to the way the arithmetic coder is implemented, it requires the probabilities in the form of integers (after suitable scaling), that's why we scale things by 10000000 in the code (you can think of these as empirical frequencies when you do 10000000 samplings).

**Comment by kv304** [comment]
cool , Thanks. One more favor , I was trying to run the GPU version of the code on Google Colab , getting CUDA 9.0 import error , any guidelines on how I can run it on GPU?

**Comment by kv304** [comment]
Getting this error on running tf2 branch

Namespace(data='../data/processed_files/SR10000.npy', gpu='0', log_file='../data/logs_data/SR10000/biLSTM.log.csv', model_name='biLSTM', name='../data/trained_models/SR10000/biLSTM.hdf5')
tcmalloc: large alloc 6791487488 bytes == 0x2b65c000 @  0x7f2c4dc6b001 0x7f2c4b0a6765 0x7f2c4b10abb0 0x7f2c4b10ca4f 0x7f2c4b1a3048 0x50a7f5 0x50cfd6 0x509918 0x50a64d 0x50c1f4 0x507f24 0x509c50 0x50a64d 0x50c1f4 0x509918 0x50a64d 0x50c1f4 0x509918 0x50a64d 0x50c1f4 0x507f24 0x50b053 0x634dd2 0x634e87 0x63863f 0x6391e1 0x4b0dc0 0x7f2c4d866b97 0x5b26fa
68
2020-09-17 10:20:20.862025: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-09-17 10:20:20.885871: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-17 10:20:20.886512: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: Tesla P4 major: 6 minor: 1 memoryClockRate(GHz): 1.1135
pciBusID: 0000:00:04.0
2020-09-17 10:20:20.886848: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-09-17 10:20:20.888074: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-09-17 10:20:20.889233: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-09-17 10:20:20.889572: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-09-17 10:20:20.890990: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-09-17 10:20:20.891995: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-09-17 10:20:20.895632: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-09-17 10:20:20.895818: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-17 10:20:20.896511: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-17 10:20:20.897126: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-09-17 10:20:20.897448: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-09-17 10:20:20.902965: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2300000000 Hz
2020-09-17 10:20:20.903206: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2c10a00 executing computations on platform Host. Devices:
2020-09-17 10:20:20.903233: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
2020-09-17 10:20:21.006281: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-17 10:20:21.006886: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2c10f40 executing computations on platform CUDA. Devices:
2020-09-17 10:20:21.006923: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Tesla P4, Compute Capability 6.1
2020-09-17 10:20:21.007152: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-17 10:20:21.007555: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: Tesla P4 major: 6 minor: 1 memoryClockRate(GHz): 1.1135
pciBusID: 0000:00:04.0
2020-09-17 10:20:21.007642: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-09-17 10:20:21.007674: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-09-17 10:20:21.007693: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-09-17 10:20:21.007735: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-09-17 10:20:21.007765: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-09-17 10:20:21.007805: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-09-17 10:20:21.007838: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-09-17 10:20:21.007954: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-17 10:20:21.008416: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-17 10:20:21.008814: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-09-17 10:20:21.008907: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-09-17 10:20:21.010036: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-09-17 10:20:21.010068: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-09-17 10:20:21.010080: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-09-17 10:20:21.010230: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-17 10:20:21.010693: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-17 10:20:21.011097: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
2020-09-17 10:20:21.011142: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7123 MB memory) -> physical GPU (device: 0, name: Tesla P4, pci bus id: 0000:00:04.0, compute capability: 6.1)
int64 float64
tcmalloc: large alloc 6391988224 bytes == 0x7f2a0b71c000 @  0x7f2c4dc691e7 0x7f2c4b0a65e1 0x7f2c4b10d420 0x7f2c4b10d682 0x7f2c4b10db3e 0x7f2c0747d0fc 0x7f2c0747e5f5 0x5517c1 0x5a9eec 0x50a783 0x50c1f4 0x507f24 0x509c50 0x50a64d 0x50c1f4 0x507f24 0x509c50 0x50a64d 0x50cfd6 0x507f24 0x509c50 0x50a64d 0x50cfd6 0x507f24 0x509c50 0x50a64d 0x50cfd6 0x507f24 0x509c50 0x50a64d 0x50cfd6
./run_experiments.sh: line 13:   543 Killed                  python trainer.py -model_name $1 -d $f -gpu $2 -name $model_file -log_file $log_file
Starting Compression ...
tcmalloc: large alloc 6791536640 bytes == 0x2a850000 @  0x7f02c3a26001 0x7f02c0c6a765 0x7f02c0ccebb0 0x7f02c0cd0a4f 0x7f02c0d67048 0x50a7f5 0x50cfd6 0x509918 0x50a64d 0x50c1f4 0x507f24 0x509c50 0x50a64d 0x50c1f4 0x509918 0x50a64d 0x50c1f4 0x509918 0x50a64d 0x50c1f4 0x507f24 0x50b053 0x634dd2 0x634e87 0x63863f 0x6391e1 0x4b0dc0 0x7f02c3621b97 0x5b26fa
2020-09-17 10:20:43.116404: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-09-17 10:20:43.160863: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-17 10:20:43.161758: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: Tesla P4 major: 6 minor: 1 memoryClockRate(GHz): 1.1135
pciBusID: 0000:00:04.0
2020-09-17 10:20:43.173475: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-09-17 10:20:43.347842: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-09-17 10:20:43.436344: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-09-17 10:20:43.453890: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-09-17 10:20:43.709209: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-09-17 10:20:43.836815: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-09-17 10:20:44.339879: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-09-17 10:20:44.340129: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-17 10:20:44.340930: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-17 10:20:44.341506: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-09-17 10:20:44.342011: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-09-17 10:20:44.393590: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2300000000 Hz
2020-09-17 10:20:44.393922: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1e52d80 executing computations on platform Host. Devices:
2020-09-17 10:20:44.393949: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
2020-09-17 10:20:44.511504: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-17 10:20:44.512073: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1e52f40 executing computations on platform CUDA. Devices:
2020-09-17 10:20:44.512109: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Tesla P4, Compute Capability 6.1
2020-09-17 10:20:44.512535: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-17 10:20:44.512976: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: Tesla P4 major: 6 minor: 1 memoryClockRate(GHz): 1.1135
pciBusID: 0000:00:04.0
2020-09-17 10:20:44.513065: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-09-17 10:20:44.513095: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-09-17 10:20:44.513121: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-09-17 10:20:44.513154: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-09-17 10:20:44.513181: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-09-17 10:20:44.513208: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-09-17 10:20:44.513237: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-09-17 10:20:44.513349: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-17 10:20:44.513930: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-17 10:20:44.514318: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-09-17 10:20:44.517810: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-09-17 10:20:44.518923: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-09-17 10:20:44.518956: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-09-17 10:20:44.518967: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-09-17 10:20:44.520104: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-17 10:20:44.520622: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-17 10:20:44.521019: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
2020-09-17 10:20:44.521075: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7123 MB memory) -> physical GPU (device: 0, name: Tesla P4, pci bus id: 0000:00:04.0, compute capability: 6.1)
Traceback (most recent call last):
  File "compressor.py", line 195, in <module>
    main()
  File "compressor.py", line 157, in main
    predict_lstm(X, Y, Y_original, timesteps, batch_size, alphabet_size, args.model_name)
  File "compressor.py", line 63, in predict_lstm
    model.load_weights(args.model_weights_file)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training.py", line 181, in load_weights
    return super(Model, self).load_weights(filepath, by_name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/network.py", line 1171, in load_weights
    with h5py.File(filepath, 'r') as f:
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '../data/trained_models/SR10000/biLSTM.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Traceback (most recent call last):
  File "decompressor.py", line 178, in <module>
    main()
  File "decompressor.py", line 147, in main
    f = open(args.input_file_prefix+'.combined','rb')
FileNotFoundError: [Errno 2] No such file or directory: '../data/compressed/SR10000/biLSTM.compressed.combined'
cmp: ../data/compressed/SR10000/biLSTM.reconstructed.txt: No such file or directory

**Comment by mohit1997** [comment]
So if you look at the following lines in the log 
```
tcmalloc: large alloc 6391988224 bytes == 0x7f2a0b71c000 @ 0x7f2c4dc691e7 0x7f2c4b0a65e1 0x7f2c4b10d420 0x7f2c4b10d682 0x7f2c4b10db3e 0x7f2c0747d0fc 0x7f2c0747e5f5 0x5517c1 0x5a9eec 0x50a783 0x50c1f4 0x507f24 0x509c50 0x50a64d 0x50c1f4 0x507f24 0x509c50 0x50a64d 0x50cfd6 0x507f24 0x509c50 0x50a64d 0x50cfd6 0x507f24 0x509c50 0x50a64d 0x50cfd6 0x507f24 0x509c50 0x50a64d 0x50cfd6
./run_experiments.sh: line 13: 543 Killed python trainer.py -model_name $1 -d $f -gpu $2 -name $model_file -log_file $log_file
```
It seems like the command being issued is killed because the program exceeded the RAM available probably. What is the length of the sequence you are trying to compress? Can you try with a smaller file?

**Comment by kv304** [comment]
I ran it successfully on Colab , using a batch size of 128 , seq length of 64 and 20 epochs.However , it takes around 20-25min on an epoch.The file size is 12 mb.Does it usually take this long to train?

**Comment by mohit1997** [comment]
You can increase the batch size you are using for training. Since the model is not overly complex, a bigger batch size usually improves training time. Other than that you can change number of epochs if you want faster compression. In any case, it will still remain much slower than gzip.

**Comment by kv304** [comment]
Hi , about the tf2 branch , I was trying to run it on Paperspace but on training there's an memory error W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 6791348224 exceeds 10% of system memory. I am using OctaCore tensorflow 2.0 container machine with 30GB of Ram.
