### ISSUE TITLE
docker install failed 

### ISSUE THREAD

**Issue by JsBlueCat** [mohit1997/DNA_Compression#9]
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/opt/conda/lib/python3.6/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/opt/conda/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 80, in do_call
        module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
      File "/opt/conda/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 678, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/opt/conda/lib/python3.6/site-packages/conda/cli/main_install.py", line 8, in <module>
        from .install import install
      File "/opt/conda/lib/python3.6/site-packages/conda/cli/install.py", line 21, in <module>
        from ..core.solve import DepsModifier, Solver
      File "/opt/conda/lib/python3.6/site-packages/conda/core/solve.py", line 14, in <module>
        from .link import PrefixSetup, UnlinkLinkTransaction
      File "/opt/conda/lib/python3.6/site-packages/conda/core/link.py", line 43, in <module>
        from ..resolve import MatchSpec
      File "/opt/conda/lib/python3.6/site-packages/conda/resolve.py", line 9, in <module>
        from tqdm import tqdm
    ModuleNotFoundError: No module named 'tqdm'

`$ /opt/conda/bin/conda install bcolz h5py matplotlib mkl nose notebook Pillow pandas pydot pygpu pyyaml scikit-learn six theano`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_DIR=/opt/conda
               CONDA_ROOT=/opt/conda
          LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64
             LIBRARY_PATH=/usr/local/cuda/lib64/stubs
                     PATH=/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sb
                          in:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
           python_version=3.6

     active environment : None
       user config file : /home/keras/.condarc
 populated config files : /home/keras/.condarc
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.6.10.final.0
       virtual packages : __glibc=2.23
       base environment : /opt/conda  (writable)
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /home/keras/.conda/pkgs
       envs directories : /opt/conda/envs
                          /home/keras/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.6.10 Linux/5.3.0-42-generic ubuntu/16.04.6 glibc/2.23
                UID:GID : 1000:100
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

**Comment by mohit1997** [comment]
Please try alternative installation (instructions updated in README) which uses python virtual environment.

**Comment by JsBlueCat** [comment]
> Please try alternative installation (instructions updated in README) which uses python virtual environment.
```bash
i motify the installtion Traceback (most recent call last):
  File "trainer.py", line 100, in <module>
    fit_model(X, Y, batch_size, num_epochs, model)
  File "trainer.py", line 86, in fit_model
    shuffle=True, callbacks=callbacks_list)
  File "/src/keras/engine/training.py", line 1213, in fit
    self._make_train_function()
  File "/src/keras/engine/training.py", line 333, in _make_train_function
    **self._function_kwargs)
  File "/src/keras/backend/tensorflow_backend.py", line 3006, in function
    v1_variable_initialization()
  File "/src/keras/backend/tensorflow_backend.py", line 420, in v1_variable_initialization
    session = get_session()
  File "/src/keras/backend/tensorflow_backend.py", line 385, in get_session
    return tf_keras_backend.get_session()
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 486, in get_session
    _initialize_variables(session)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 903, in _initialize_variables
    [variables_module.is_variable_initialized(v) for v in candidate_vars])
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'CudnnRNN' used by node bidirectional_1/CudnnRNN (defined at /opt/conda/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) with these attrs: [dropout=0, seed=42, input_mode="linear_input", T=DT_FLOAT, direction="unidirectional", rnn_mode="gru", seed2=0, is_training=true]
Registered devices: [CPU, XLA_CPU]
Registered kernels:
  device='GPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_HALF]
```
but in python i use 
import tensorflow as tf 
print(tf.test.is_gpu_available()) 
it print True 
i use cuda10 
so  can you give me some suggestions?

also i test in keras it prints out :
```python
2020-03-22 00:11:44.773383: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10063 MB memory) -> physical GPU (device: 0, name: TITAN V, pci bus id: 0000:65:00.0, compute capability: 7.0)
['/job:localhost/replica:0/task:0/device:GPU:0']
```

**Comment by mohit1997** [comment]
What command are you using to run the experiments?

```bash 
./run_experiments.sh biLSTM 0
```
Please use the above command where 0 is the GPUID. If you have multiple GPUs (N) you can use id from 0 to N-1.

Thanks for pointing it out.

**Comment by JsBlueCat** [comment]
> What command are you using to run the experiments?
> 
> ```shell
> ./run_experiments.sh biLSTM 0
> ```
> 
> Please use the above command where 0 is the GPUID. If you have multiple GPUs (N) you can use id from 0 to N-1.
> 
> Thanks for pointing it out.


i run this command 
./run_experiments.sh biGRU_big

another error appear:
```python
Epoch 1/20
2020-03-22 00:30:12.803233: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-03-22 00:30:13.219259: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-03-22 00:30:14.481737: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2020-03-22 00:30:14.481841: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at cudnn_rnn_ops.cc:1510 : Unknown: Fail to find the dnn implementation.
2020-03-22 00:30:14.494450: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2020-03-22 00:30:14.494518: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at cudnn_rnn_ops.cc:1510 : Unknown: Fail to find the dnn implementation.
Traceback (most recent call last):
  File "trainer.py", line 100, in <module>
    fit_model(X, Y, batch_size, num_epochs, model)
  File "trainer.py", line 86, in fit_model
    shuffle=True, callbacks=callbacks_list)
  File "/src/keras/engine/training.py", line 1239, in fit
    validation_freq=validation_freq)
  File "/src/keras/engine/training_arrays.py", line 196, in fit_loop
    outs = fit_function(ins_batch)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 3476, in __call__
    run_metadata=self.run_metadata)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1472, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Fail to find the dnn implementation.
         [[{{node bidirectional_1/CudnnRNN_1}}]]
         [[Mean/_141]]
  (1) Unknown: Fail to find the dnn implementation.
         [[{{node bidirectional_1/CudnnRNN_1}}]]
0 successful operations.
0 derived errors ignored.
```

and i fail to find cudnn in docker~~

```bash 
cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2 
cat: /usr/local/cuda/include/cudnn.h: No such file or directory
```

**Comment by mohit1997** [comment]
Please try to run

```bash
./run_experiments.sh biGRU_big 0
```

**Comment by JsBlueCat** [comment]
can't find cudnn

cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2 
cat: /usr/local/cuda/include/cudnn.h: No such file or directory

**Comment by mohit1997** [comment]
Are you still using the docker?
Also, you do require CUDNN library. 
[Instructions](https://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html)

Once you have that,
Run this command to verify your installation
```bash
cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2
```

Once that is working,
can you do a fresh clone and repeat the steps and then run the following command?

```bash
./run_experiments.sh biLSTM 0
```

**Comment by JsBlueCat** [comment]
> Are you still using the docker?
> Can you do a fresh clone and repeat the steps and then run the following command?
> 
> ```shell
> ./run_experiments.sh biLSTM 0
> ```

i run in docker with  tf=1.15 cuda=10.0 and run ./run_experiments.sh biGRU_big 0

**Comment by mohit1997** [comment]
Please follow the previous comment. For this code to run you require TensorFlow 1.8
With TensorFlow 1.15 you might need to change certain commands which are deprecated.

**Comment by JsBlueCat** [comment]
> Please follow the previous comment. For this code to run you require TensorFlow 1.8
> With TensorFlow 1.15 you might need to change certain commands which are deprecated.

thank you i will have a try :)

**Comment by JsBlueCat** [comment]
> Please follow the previous comment. For this code to run you require TensorFlow 1.8
> With TensorFlow 1.15 you might need to change certain commands which are deprecated.
```bash
Traceback (most recent call last):
  File "decompressor.py", line 20, in <module>
    import keras
  File "/src/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/src/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/src/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/src/keras/backend/__init__.py", line 1, in <module>
    from .load_backend import epsilon
  File "/src/keras/backend/load_backend.py", line 90, in <module>
    from .tensorflow_backend import *
  File "/src/keras/backend/tensorflow_backend.py", line 13, in <module>
    from tensorflow.python.keras.utils import tf_utils
ImportError: cannot import name 'tf_utils'
```

so what's your keras version???

**Comment by mohit1997** [comment]
Use `pip install keras==2.2.2`.

**Comment by JsBlueCat** [comment]
> pip install keras==2.2.2

  ERROR: Cannot unpack file /tmp/pip-unpack-e9wh51hs/simple.htm (downloaded from /tmp/pip-req-build-bs731y8o, content-type: text/html); cannot detect archive format
ERROR: Cannot determine archive format of /tmp/pip-req-build-bs731y8o

**Comment by JsBlueCat** [comment]
> Use `pip install keras==2.2.2`.

question also exsist 
Traceback (most recent call last):
  File "compressor.py", line 20, in <module>
    import keras
  File "/src/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/src/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/src/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/src/keras/backend/__init__.py", line 1, in <module>
    from .load_backend import epsilon
  File "/src/keras/backend/load_backend.py", line 90, in <module>
    from .tensorflow_backend import *
  File "/src/keras/backend/tensorflow_backend.py", line 13, in <module>
    from tensorflow.python.keras.utils import tf_utils
ImportError: cannot import name 'tf_utils'

**Comment by mohit1997** [comment]
The error is because of the keras version.
What is your python version?
Are you using the python virtual environment?
If not, you can install keras 2.2.2 in the same fashion as you did other packages?

Ideally, this command should take care of everything
```bash 
cd DeepZip
python3 -m venv tf
source tf/bin/activate
bash install.sh
```

**Comment by JsBlueCat** [comment]
> The error is because of the keras version.
> What is your python version?
> Are you using the python virtual environment?
> If not, you can install keras 2.2.2 in the same fashion as you did other packages?
> 
> Ideally, this command should take care of everything
> 
> ```shell
> cd DeepZip
> python3 -m venv tf
> source tf/bin/activate
> bash install.sh
> ```

COPY keras-2.2.2 /src
RUN pip install -e /src[tests] -i http://pypi.douban.com/simple --trusted-host pypi.douban.com
RUN pip install git+git://github.com/keras-team/keras.git@v2.2.2 -i http://pypi.douban.com/simple --trusted-host pypi.douban.com && \
  conda clean -yt

i change your docker with this command

**Comment by JsBlueCat** [comment]
> The error is because of the keras version.
> What is your python version?
> Are you using the python virtual environment?
> If not, you can install keras 2.2.2 in the same fashion as you did other packages?
> 
> Ideally, this command should take care of everything
> 
> ```shell
> cd DeepZip
> python3 -m venv tf
> source tf/bin/activate
> bash install.sh
> ```

run success !!! thank you , it is a very very very nice job !!!!
